[tool.poetry]
name = "gizmo"
version = "0.6"
description = "Gizmo code dags"
authors = ["algol60 <algol60@users.noreply.github.com>"]
readme = "README.rst"
packages = [{include = "gizmo", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"

param = "^2.0"

[tool.poetry.plugins."gizmo.library"]
export = "gizmo.provided:gizmos"

[[tool.mypy.overrides]]
module = [
    "holoviews",
    "param"
]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
